server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: wehcat-demo
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  mvc:
    dispatch-options-request: true
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wechat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    servlet:
      multipart:
        max-file-size: 2MB
        max-request-size: 20MB

wechat:
  appId: wx84afcdc3663b8cc1
  secretId:
  secretKey: 6603c67df263dd425749e6b24c198df5

# 上传文件相关配置 F:/image/
upload:
  filePath: /home/image/


logging:
  level:
    com.wechat.demo.mapper: debug

